In [16]:
using Plots
using Statistics
using LinearAlgebra
using JSON

include("readclassjson.jl");


## 11.1830 Estimating a matrix with known eigenvectors

Carry out your method with the data
$$
A^{\text {meas }}=\left[\begin{array}{ccc}
2.0 & 1.2 & -1.0 \\
0.4 & 2.0 & -0.5 \\
-0.5 & 0.9 & 1.0
\end{array}\right], \quad v_{1}=\left[\begin{array}{c}
0.7 \\
0 \\
0.7
\end{array}\right], \quad v_{2}=\left[\begin{array}{c}
0.3 \\
0.6 \\
0.7
\end{array}\right], \quad v_{3}=\left[\begin{array}{c}
0.6 \\
0.6 \\
0.3
\end{array}\right]
$$
Be sure to check that $\hat{A}$ does indeed have $v_{1}, v_{2}, v_{3}$ as eigenvectors, by (numerically) finding its eigenvectors and eigenvalues. Also, give the value of $J$ for $\hat{A}$.You

In [69]:
Am = [2 1.2 -1 ; 0.4 2.0 -0.5 ; -0.5 0.9 1]

3×3 Array{Float64,2}:
  2.0  1.2  -1.0
  0.4  2.0  -0.5
 -0.5  0.9   1.0

In [75]:
Am_vec = Am[:];

In [4]:
v1 = [0.7 ; 0 ; 0.7]
v2 = [0.3 ; 0.6 ; 0.7]
v3 = [0.6 ; 0.6 ; 0.3];

In [153]:
eigenV = [v1 v2 v3]

3×3 Array{Float64,2}:
 0.7  0.3  0.6
 0.0  0.6  0.6
 0.7  0.7  0.3

In [154]:
eigenW = inv(eigenV)

3×3 Array{Float64,2}:
  0.816327  -1.12245    0.612245
 -1.42857    0.714286   1.42857
  1.42857    0.952381  -1.42857

In [156]:
V = reduce(hcat, [(eigenV[:,i] * transpose(eigenW[i,:]))[:] for i in [1, 2, 3]])

9×3 Array{Float64,2}:
  0.571429  -0.428571   0.857143
  0.0       -0.857143   0.857143
  0.571429  -1.0        0.428571
 -0.785714   0.214286   0.571429
 -0.0        0.428571   0.571429
 -0.785714   0.5        0.285714
  0.428571   0.428571  -0.857143
  0.0        0.857143  -0.857143
  0.428571   1.0       -0.428571

In [159]:
svd([V Am_vec])

SVD{Float64,Float64,Array{Float64,2}}
U factor:
9×4 Array{Float64,2}:
  0.549067   -0.177995   0.473132   -0.57366
  0.183579   -0.422562  -0.0757833   0.323742
 -0.0828244  -0.493873   0.251226    0.452548
  0.355616    0.104417  -0.45149    -0.110721
  0.52914     0.198067   0.142604    0.448608
  0.255203    0.231334  -0.445839    0.199265
 -0.332188    0.204347   0.283797    0.0823211
 -0.207111    0.4142     0.0640178  -0.0730018
  0.182043    0.478415   0.446876    0.309813
singular values:
4-element Array{Float64,1}:
 3.881561728035197
 2.490178609079442
 1.4967333638812184
 0.12051216428058734
Vt factor:
4×4 Array{Float64,2}:
 -0.0715828  -0.00440834   0.400667   0.913412
 -0.142607    0.833796    -0.491008   0.208228
  0.956823   -0.0161787   -0.23069    0.176099
  0.24296     0.551818     0.738349  -0.302172

In [160]:
lambda = V \ Am_vec

3-element Array{Float64,1}:
 0.7840290263886044
 1.80014104068647
 2.4158299329249253

In [161]:
Ahat = reshape(V * lambda, 3, 3)

3×3 Array{Float64,2}:
  1.74724   1.1502    -0.96321
  0.527733  2.15196   -0.527733
 -0.316769  0.974285   1.1008

In [169]:
eigen(Ahat)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
 0.7840290263886041
 1.80014104068647
 2.4158299329249258
vectors:
3×3 Array{Float64,2}:
 0.707107     0.309426  -0.666667
 3.60822e-16  0.618853  -0.666667
 0.707107     0.721995  -0.333333

Relatively close to the eigendecomposition

In [168]:
abs.(eigen(Ahat).vectors) .- eigenV

3×3 Array{Float64,2}:
 0.00710678   0.00942637  0.0666667
 3.60822e-16  0.0188527   0.0666667
 0.00710678   0.0219949   0.0333333

In [119]:
Ahat * v2 

3-element Array{Float64,1}:
 1.1890047663086005
 1.455877320907733
 0.42967453937540034

In [170]:
J = (1/9) * sum((Am .- Ahat).^2)

0.017461333438605432