In [1]:
using Plots
using Statistics
using LinearAlgebra
using JSON

include("readclassjson.jl");

\begin{align*}
A=\left[\begin{array}{ccc}
-0.9 & -4.2 & -2 \\
1 & 0 & 0 \\
0 & 1 & 0
\end{array}\right], \quad C=\left[\begin{array}{ccc}
1 & 0 & -1 \\
0 & 1 & 1
\end{array}\right]
\end{align*}

In [4]:
A = [-0.9 -4.2 -2 ; 1 0 0 ; 0 1 0]
C = [1 0 -1 ; 0 1 1]

2×3 Array{Int64,2}:
 1  0  -1
 0  1   1

In [17]:
y_1_matrix = reduce(vcat, [C[1,:]' * exp(A .* t) for t in [1.0195, 3.0288, 4.0863, 6.4176, 6.9723]])

5×3 Array{Float64,2}:
 -0.816326   -1.99085   -1.24183
  0.63736     0.38533   -0.13163
 -0.328734   -1.13316   -0.581612
  0.292682   -0.130546  -0.168747
 -0.0203417  -0.625948  -0.330852

In [18]:
y_2_matrix = reduce(vcat, [C[2,:]' * exp(A .* t) for t in [0.9210, 1.9402]])

2×3 Array{Float64,2}:
  0.523163   0.316825   0.343106
 -0.123144  -0.739255  -0.149319

In [19]:
total_matrix = vcat(y_1_matrix, y_2_matrix)

7×3 Array{Float64,2}:
 -0.816326   -1.99085   -1.24183
  0.63736     0.38533   -0.13163
 -0.328734   -1.13316   -0.581612
  0.292682   -0.130546  -0.168747
 -0.0203417  -0.625948  -0.330852
  0.523163    0.316825   0.343106
 -0.123144   -0.739255  -0.149319

In [20]:
y_vals = ones(7, 1)

7×1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [23]:
x0 = total_matrix \ y_vals

3×1 Array{Float64,2}:
  2.8000085666483163
 -1.8998215255717283
  0.39975403221356076

In [27]:
x0 = total_matrix[1:3,:] \ y_vals[1:3,:]

3×1 Array{Float64,2}:
  2.800795474309895
 -1.9006483447480866
  0.4006529597835425

For a consistent set of equations, the left inverse produces an exact solution, not an approximate one. We can see below that the solution produces the y values with some floating point error. Additionally, basing our solution just on say the first three equations produced nearly the same estimates. And finally, our test $y = Q_1Q_1^Ty$ appears true, therefore y lies in range of our "total_matrix". 

In [45]:
F = qr(total_matrix)
F.Q[:,1:3] * F.Q[:,1:3]' * y_vals

7×1 Array{Float64,2}:
 1.0001126138100727
 0.9999353807219192
 0.9998445908112364
 1.0000674646734078
 0.9999726817581848
 1.0001083106816497
 0.9999588978156284

In [24]:
total_matrix * x0

7×1 Array{Float64,2}:
 1.0001126138100742
 0.9999353807219196
 0.9998445908112371
 1.000067464673408
 0.9999726817581855
 1.0001083106816497
 0.9999588978156289

Finally, the exact solution to $||x(T)||$ is below

In [31]:
T = 10
xT = exp(A .* T)x0

3×1 Array{Float64,2}:
  0.48692034806057316
  0.03415720077628341
 -0.11900897260050991

In [33]:
norm(xT)

0.5024154409248685