In [2]:
x = 1 + 1

2

In [7]:
"x"[1]

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [16]:
SubString("xxxxxcxxx", 2, 6)

"xxxxc"

In [17]:
?SubString

search: SubString SubstitutionString



```
SubString(s::AbstractString, i::Integer, j::Integer=lastindex(s))
SubString(s::AbstractString, r::UnitRange{<:Integer})
```

Like [`getindex`](@ref), but returns a view into the parent string `s` within range `i:j` or `r` respectively instead of making a copy.

# Examples

```jldoctest
julia> SubString("abc", 1, 2)
"ab"

julia> SubString("abc", 1:2)
"ab"

julia> SubString("abc", 2)
"bc"
```


In [24]:
function z(x, y)
    r  = x + y
    return r - 2
end

z (generic function with 1 method)

In [25]:
z(1,2)

1

In [18]:
f(x) = 1 + x

f (generic function with 1 method)

In [19]:
f(2)

3

In [29]:
function hypot(x,y)::Float32
   x = abs(x)
   y = abs(y)
   if x > y
       r = y/x
       return x*sqrt(1+r*r)
   end
   if y == 0
       return zero(x)
   end
   r = x/y
   return y*sqrt(1+r*r)
end

hypot (generic function with 1 method)

In [30]:
hypot(2,3)

3.6055512f0

In [31]:
function printx(x)
    println("x = $x")
    return nothing
end

printx (generic function with 1 method)

In [32]:
+(1,2,3,4)

10

In [34]:
b = [6 7; 8 9; 10 11; 12 13; 14 15]
a = [1; 2; 3; 4; 5]
hcat(a,b)

5×3 Array{Int64,2}:
 1   6   7
 2   8   9
 3  10  11
 4  12  13
 5  14  15

In [35]:
x -> x^2 + 2x - 1

#1 (generic function with 1 method)

In [38]:
map(x -> x^2 + 2x - 1, [1, 3, -1])

3-element Array{Int64,1}:
  2
 14
 -2

In [39]:
x = (a=2, b=1+2); x.a

2

In [42]:
minmax(x, y) = (y < x) ? (y, x) : (x, y); minmax(2,1)

(1, 2)

In [43]:
using Dates
Date(2000, 12, 12)

2000-12-12

In [44]:
map([A, B, C]) do x
    if x < 0 && iseven(x)
        return 0
    elseif x == 0
        return 1
    else
        return x
    end
end

LoadError: UndefVarError: A not defined

In [ ]:
\circ

In [ ]:
open("outfile", "w") do io
    write(io, data)
end

In [45]:
map(first ∘ reverse ∘ uppercase, split("you can compose functions like this"))

6-element Array{Char,1}:
 'U': ASCII/Unicode U+0055 (category Lu: Letter, uppercase)
 'N': ASCII/Unicode U+004E (category Lu: Letter, uppercase)
 'E': ASCII/Unicode U+0045 (category Lu: Letter, uppercase)
 'S': ASCII/Unicode U+0053 (category Lu: Letter, uppercase)
 'E': ASCII/Unicode U+0045 (category Lu: Letter, uppercase)
 'S': ASCII/Unicode U+0053 (category Lu: Letter, uppercase)

In [46]:
# broadcasting
["a", "list", "of", "strings"] .|> [uppercase, reverse, titlecase, length]

4-element Array{Any,1}:
  "A"
  "tsil"
  "Of"
 7

In [49]:
#vectorizing functions
A = [1.0, 2.0, 3.0]
sin.(A)
f(x,y) = 3x + 4y;
f.(pi, A)

3-element Array{Float64,1}:
 13.42477796076938
 17.42477796076938
 21.42477796076938

In [51]:
l = begin
       x = 1
       y = 2
       x + y
   end

3

In [52]:
if x < y
    println("x is less than y")
elseif x > y
    println("x is greater than y")
else
    println("x is equal to y")
end

x is less than y


In [54]:
vector = [3; 4; 5];

In [55]:
vector[2:3]

2-element Array{Int64,1}:
 4
 5

In [60]:
?avg

search:

Couldn't find avg
Perhaps you meant a, ans, Aug, abs, all, any, big, log, mv, A, Apr, abs2 or acos


No documentation found.

Binding `avg` does not exist.


In [62]:
using Statistics 
using LinearAlgebra

# Useful functions
@show sum(vector)
@show mean(vector)

# Ones vector
@show ones(3)

# Zeros vector
@show zeros(3)

# Unit vectors
e2 = zeros(3)
e2[2] = 1
@show e2

# Inner products
a = [1; 4; 0]
b = [-1; 3; 2]

@show dot(a, b)
@show a' * b
@show a'b

# Vector addition and scalar multiplication
@show 2*a + b

# Adding a scalar to a vector (note the .)
@show a .+ 4;

sum(vector) = 12
mean(vector) = 4.0
ones(3) = [1.0, 1.0, 1.0]
zeros(3) = [0.0, 0.0, 0.0]
e2 = [0.0, 1.0, 0.0]
dot(a, b) = 11
a' * b = 11
a' * b = 11
2a + b = [1, 11, 2]
a .+ 4 = [5, 8, 4]
